version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - lnmp
  php72:
    image: php:7.2.3-fpm
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html
      - ./log/php72:/var/log/php
      - ./conf/php72:/usr/local/etc/php
    environment:
      - TZ=Asia/Shanghai
    networks:
      - lnmp
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    networks:
      - lnmp
networks:
  lnmp:
